### ISSUE TITLE
Crash "pew wipeenv venv" like "pew rm venv"

### ISSUE THREAD

**Issue by BartGo** [berdario/pew#104]
Please consider a bash script in "strict mode" (*)

```
set -euo pipefail
IFS=$'\n\t'

VENV_NAME=venv

pew wipeenv $VENV_NAME
pew rm      $VENV_NAME
pew new -d  $VENV_NAME
pew in      $VENV_NAME pip install --upgrade blahblah
```

If the venv does not exist the script will show
`
ERROR: Environment 'venv' does not exist.
`
and exit.

If we comment out the line with wipeenv and run the script (with not existing venv), the script will NOT crash at rm, the result will be:
`
Error while trying to remove the d:\Users\myuser\.local\share\virtualenvs\venv env:
The system cannot find the path specified
`
but the bash script will continue. 

I think that the reason is that wipenv returns a different error code from rm or otherwise crashes in less pleasant way.

I suggest that wipeenv crashes in the same way as rm, for consistency.

I checked the above on Windows 10 with Git's GNU bash, version 3.1.23(6), no access to Linux today but probably it would work in the same way.

(*)
http://redsymbol.net/articles/unofficial-bash-strict-mode/

**Comment by berdario** [comment]
I fixed this. I went in the opposite direction you suggested (that is, `pew rm` is now as strict as `pew wipeenv`).

so, if you'd now want to ignore errors in pew commands in a bash script you could use `|| true` or `|| :` (if you prefer bashisms)

```
pew wipeenv $VENV_NAME || true
pew rm      $VENV_NAME || true
```

Unfortunately this is one of the cases in which a type checker would've helped to avoid forgetting to return the proper error code. In all my new projects I try to use mypy and Python3.5... but unfortunately I cannot be as bold here if I want to keep compatibility with old versions of Python (and type checking without annotation syntax is just ugly)

Thanks for reporting the issue, and sorry for not acting on it earlier.

**Comment by BartGo** [comment]
Thanks for the fix!!
