### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Lucas-C** [berdario/pew#107]
Hello,

Could it be possible to release a new version in order to integrate this fix please ?
https://github.com/berdario/pew/issues/94

Regards

**Comment by berdario** [comment]
Done!

Sorry for the delay...
I changed job (again!) and nowadays I keep using my work laptop even when home (and my pypi setup is on my personal machine), otherwise I'd have done the release yesterday already

**Comment by Lucas-C** [comment]
No problem, thank you ;)
