### ISSUE TITLE
Corner case bug : pew workon ~

### ISSUE THREAD

**Issue by Lucas-C** [berdario/pew#108]
Hi,

`pew workon ~` never crashes, while it definitively should :)
The same happens each time an existing absolute path is passed as an argument to `pew workon`.

The reason is hidden on this line:
https://github.com/berdario/pew/blob/master/pew/pew.py#L312

```bash
$ python -c "from pathlib import Path; print((Path('I do not exist') / '/tmp').exists())"
True
```

**Comment by berdario** [comment]
Nice catch!

Since I've been neglecting pew a bit lately, would you like commit access to fix things like these, merge PR, etc?

**Comment by Lucas-C** [comment]
Thanks for the proposition :)
I can just submit a PR this time, unless you think you won't have time to review it.
It's not a blocking bug
