### ISSUE TITLE
Missing dependency in requirements.txt 

### ISSUE THREAD

**Issue by Lucas-C** [berdario/pew#115]
`pythonz-bd` is specified as a dependency in [`setup.py`](https://github.com/berdario/pew/blob/master/setup.py#L26) but is missing in [`requirements.txt`](https://github.com/berdario/pew/blob/master/requirements.txt).
Also `pytest` should probably be in a separate `dev-requirements.txt`.

A solution to keep those requirements in sync is to put the following in your `setup.py` :
```
with open(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'requirements.txt')) as file_requirements:
    requirements = file_requirements.readlines()
```
Just make sure the `requirements.txt` is included in the Pypi package (using `MANIFEST.in`).

**Comment by berdario** [comment]
Uhm, I use `requirements.txt` only to pin down specific versions of the dependencies, and it's thus used only in development. I don't think I'll split it into a `dev-requirements.txt`

A few years ago I also thought that I should deduplicate the information written in `requirements.txt` and `setup.py`... reading the file as you suggest is the same approach used by [pbr](http://docs.openstack.org/developer/pbr/) after all. But I now think that's the wrong approach and that a turing-complete setup.py is a mistake.

Most importantly, you don't want to pin the dependencies in `setup.py` to a specific version.

Anyhow, thanks for pointing out the missing deps! I'll fix the `requirements.txt` this evening
