### ISSUE TITLE
pew Failing To Enter Virtual Environment

### ISSUE THREAD

**Issue by tundratim** [berdario/pew#118]
Attempt to enter newly-created or existing virt environment blows out on some of our systems - so far seen on one FreeBSD 10-STABLE VPS and one CentOS VPS.  It seems fine on FreeBSD-Stable on physical machines, Linux Mint 17/Physical, and CentOS7/VPS.  Details:

```
~>pew workon foo
Traceback (most recent call last):
  File "/usr/local/bin/pew", line 11, in <module>
    sys.exit(pew())
  File "/usr/local/lib/python2.7/site-packages/pew/pew.py", line 738, in pew
    return command(sys.argv[2:])
  File "/usr/local/lib/python2.7/site-packages/pew/pew.py", line 355, in workon_cmd
    shell(env, cwd=project_dir)
  File "/usr/local/lib/python2.7/site-packages/pew/pew.py", line 200, in shell
    fork_bash(env, cwd)
  File "/usr/local/lib/python2.7/site-packages/pew/pew.py", line 157, in fork_bash
    with NamedTemporaryFile('w+') as rcfile:
  File "/usr/local/lib/python2.7/site-packages/pew/_utils.py", line 27, in NamedTemporaryFile
    return getwriter(encoding)(_ntf(mode))
  File "/usr/local/lib/python2.7/codecs.py", line 1009, in getwriter
    return lookup(encoding).streamwriter
TypeError: lookup() argument 1 must be string, not None
```

**Comment by berdario** [comment]
Judging by the stacktrace, this happens because you don't have an encoding set in your locale

**Comment by tundratim** [comment]
That was my instinct too, but both BSD boxes were set up more-or-less the same (neither had $LANG set) and all the Centos6 and 7 machines - bot those working with pew, and those not working - had $LANG set to 'C'.

In any case, I changed $LANG appropriately for each environment and ... you're right ... it's fixed.

Very strange.  Closing ticket... and thanks ;)

**Comment by berdario** [comment]
Good  :) 

Is it possible that on the other boxes Pew might have been installed under Python3? That would explain why elsewhere it could work
-- 
Sent from mobile. Please excuse my brevity.

**Comment by tundratim** [comment]
On 08/31/2016 06:40 PM, berdario wrote:
> Is it possible that on the other boxes Pew might have been installed under Python3?


Nope, I installed pip on Py2 myself.
----------------------------------------------------------------------------
Tim Daneliuk     tundra@tundraware.com
PGP Key:         http://www.tundraware.com/PGP/

**Comment by kiransubash** [comment]
I seem to have hit the same issue, but I do have a LANG set up. 

[vagrant@csar-build ~]$ echo $LANG
en_US.UTF-8

This is on a vagrant Centos 6 box, and I installed Python 2.7 under /usr/local and also pip/pew under the same path.

**Comment by berdario** [comment]
Good, but why  "automatically set locale environment" sets it as C (which only allows ASCII)?

I guess that at the very least I should provide a better error message

**Comment by kiransubash** [comment]
I am unsure why it gets set to C automatically, but I believe its something to do with the OSX terminal. Perhaps my default locale on OSX is not set correctly. If I do find the answer I will post it here. Thank you for your work on pew.

**Comment by tundratim** [comment]
With OSX, I found that setting $LANG explicitly in my .bashrc (to  en_US.ISO8859-1 in my case) mad this problem disappear.

I agree that a somewhat more descriptive error message might be indicated.

**Comment by berdario** [comment]
@tundratim 
Is  `en_US.ISO8859-1` correct for you? Don't you use unicode?

**Comment by tundratim** [comment]
This was just to prove that the fix worked.
