### ISSUE TITLE
PPA doesn't work

### ISSUE THREAD

**Issue by caswitch** [berdario/pew#119]
I tried to install pew on Ubuntu16.04 following "Ubuntu PPA" instructions.

When I execute "sudo apt-get update" I have this error :
Failed to fetch http://ppa.launchpad.net/pew-maintainers/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found

**Comment by berdario** [comment]
Uhm, I'm afraid that it was never packaged for Xenial  :/

I opened an issue to keep track of [this](https://github.com/berdario/pew/issues/40) 

Sorry, but if no one picks that up, I'm afraid it might just be better to remove mention of a PPA from the README  :/
