### ISSUE TITLE
error in docker-py setup command: ivalid environment marker:python_version < "3.5" when installed docker-py-1.9.0

### ISSUE THREAD

**Issue by fw0037** [berdario/pew#126]
the environment is:

**python 2.7.5
requests-2.10.0
six-1.10.0
websocket_client-0.37.0
backports.ssl_match_hostname-3.5.0.1
ipaddress-1.0.17
docker 1.12.1**

When I installed the docker-py-1.9.0 using **"python setup.py build"**, it is shown below：
**error in docker-py setup command: ivalid environment marker:python_version < "3.5"**

Why is this error message, how to fix it? Thanks.

**Comment by berdario** [comment]
I think this is a problem for [docker-py](https://github.com/docker/docker-py)

You can probably fix it by updating your version of setuptools
