### ISSUE TITLE
Document version dependency for bash-completion

### ISSUE THREAD

**Issue by systemexitzero** [berdario/pew#128]
I'm working on a system without (modern) bash-completion installed, so the following scenario gives me an error when attempting tab completion:

``` sh
$ source $(pew shell_config)
$ pew _init_completion: command not found

Display all 166 possibilities? (y or n)
```

I see in that _init_completion was added in https://github.com/scop/bash-completion/commit/32dbe76784acc39b17ee9ca7bc21c28f4f2b23b5 which is tagged with a minimum version of 1.9

Where would make the most sense to document this (non-essential) dependency?

**Comment by berdario** [comment]
> Where would make the most sense to document this (non-essential) dependency?

Good question

Aside from the README, I'm not sure where else this information could be shown

(frankly, I thought that `_init_completion` might've been supplied by `bash`, itself... I haven't thought too much about these details concerning autocompletion)
