### ISSUE TITLE
pew in should support shell aliases

### ISSUE THREAD

**Issue by Phyks** [berdario/pew#129]
Hi,

I have some alias in my `.zshrc` for `jupyter-notebook` (typically `alias jupyter-notebook="jupyter-notebook --no-browser"`).

It seems for some reason `pew in` does not allow the use of shell aliases. Would it be possible to add support for this? (I guess this is because `pew in` actually never spawn a new shell, so the shell never has any chance at doing the alias job).

Thanks

**Comment by berdario** [comment]
Uhm, yeah `pew in` expects an executable.. shell functions and aliases won't work.

To be able to support this, we'd need to be able to find a way to obtain all of the aliases (and functions!) currently defined in the invoking shell... even if that's possible, it would be different for every shell and add quite a bit of complexity

If truly needed, I think that `pew in env sh -c 'your_alias'` would work.

Sorry, but I don't think I have a better solution

**Comment by Phyks** [comment]
OK. I was thinking that maybe pew in could spawn a shell and run the command inside rather than executing the executable directly. Thanks
