### ISSUE TITLE
modules from 'pew add <dir>' are preferred over local modules

### ISSUE THREAD

**Issue by dajuno** [berdario/pew#130]
Hello,

I use python on a HPC cluster. There is a system python (old and without packages), and python 2.7 provided via a "module" that can be loaded, including some optimized packages like numpy.

So, using this python 2.7, I make a virtualenv with pew. Inside this virtualenv I install some  "custom" packages I need using `pip install`. Since I also want to use the cluster modules, I add the (non-standard) location of the site-packages folder via `pew add`.
Now, unfortunately, this folder contains one module that conflicts with a custom module (same name coincidentally). The virtualenv python session always prefers the module from the folder added with `pew add`. The custom module is not found.

Is there anything I can do? (renaming is not an option)

Thanks!

**Comment by berdario** [comment]
I don't know enough about your situation, so I guess there should be a cleaner solution, but... let's assume that `/tmp/foo` is the directory that you added via `pew add`

You could simply do

```
import sys
sys.path.remove('/tmp/foo')
sys.path.append('/tmp/foo')
```

as long as a module inside `/tmp/foo` (except the problematic one) is not shadowed by another package installed in the virtualenv. This should solve the problem by picking the virtualenv modules first

Maybe you could also `pip install -e` the cluster modules?

Also, maybe you could symlink the module that you care about from another directory, and only add this other directory with `pew add` ?

**Comment by dajuno** [comment]
You are right, it's quite specific. Maybe the cluster admins have an idea how to do this cleanly. I though it was maybe connected to my use of pew.
All your recommendations are good ideas really, I'll try this. Thanks a lot :)
(pip install -e unfortunately does not work though because not all cluster modules are 'installable' with a setup.py)
