### ISSUE TITLE
Deprecation warning on --allow-all-external

### ISSUE THREAD

**Issue by Lucas-C** [berdario/pew#131]
I get the following red warning when using pew with pip version 9.0.1

```
DEPRECATION: --allow-all-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
```

From https://pip.pypa.io/en/stable/news/ :

> 8.0.0 (2016-01-19)
> Deprecate and no-op the --allow-external, --allow-all-external, and --allow-unverified functionality that was added as part of PEP 438. With changes made to the repository protocol made in PEP 470, these options are no longer functional.

I think this option was added as part of #23, is this needed anymore ?

**Comment by berdario** [comment]
Yup, we can remove it... thanks for pointing it out

If someone thinks they still need this functionality:

https://www.python.org/dev/peps/pep-0470/#i-can-t-host-my-project-on-pypi-because-of-x-what-should-i-do

https://gist.github.com/Jaza/fcea493dd0ba6ebf09d3
