### ISSUE TITLE
add command to return path to virutalenv

### ISSUE THREAD

**Issue by kennethreitz** [berdario/pew#133]
e.g. 

```
$ pew dir myenv
/Users/kennethreitz/.virtualenvs/myenv

**Comment by berdario** [comment]
👍 Will do it tomorrow

**Comment by kennethreitz** [comment]
@berdario thanks! I'd like to use pew for `pipenv`, but `pew workon` doesn't seem to work on my machine, wish zsh. 

It would be nice, because I'm currently trying to get windows users to be able to run `$ pipenv shell`.

**Comment by ryanhiebert** [comment]
What does it do, so that you're saying it's not working? Is it throwing an error?

**Comment by kennethreitz** [comment]
no error, it simply doesn't activate the virtualenv — just gives me a new shell

**Comment by ryanhiebert** [comment]
You might want to check on that, and make sure it's not activated. I suspect that what you're seeing is the biggest gotcha with the subshell approach: it sources your init scripts, including your PS1 (or whatever the equivalent is for zsh). This means that it doesn't add the customary venv name to the beginning of your prompt.

In my virtualenvs, I just want to know that I have it activated, so I have it add a 🐍 to my fish prompt. This is what my fish config looks like. It has to check whether it's in a virtualenv:

```fish
function fish_prompt
  if [ -n "$VIRTUAL_ENV" ]
    echo -n '🐍 '
  end
  echo -n '🐟  '
end
```

**Comment by ryanhiebert** [comment]
Oh, and that variable (`VIRTUAL_ENV`) has the full path to your virtualenv, so you could use something like this to get the path to the virtualenv:

```
pew in my-virtualenv python -c "import os; print(os.environ.get('VIRTUAL_ENV'), '')"
```

Which would print the virtualenv path, or an empty line.

**Comment by ryanhiebert** [comment]
@kennethreitz : Did you figure this out? Is there any way that I can assist?

**Comment by berdario** [comment]
Done! (and pushed a new version on pypi)
