### ISSUE TITLE
Pew not working with "fish" installed from Macports.

### ISSUE THREAD

**Issue by mbaechtold** [berdario/pew#147]
`/opt/local` is the default install location for `Macports` (see https://trac.macports.org/wiki/FAQ#defaultprefix) that's why I used to add `/opt/local/bin` and `/opt/local/sbin` to `$PATH` (at least for `bash` and `zsh`).

But I recently switched to `fish`.

`Macports` patches `config.fish` so that `/opt/local/bin` is always at the head of `$PATH`, see https://github.com/macports/macports-ports/blob/62d26f57eaf2e671acd0983a26d521ab6daff143/shells/fish/files/patch-share_config_fish.diff.

Manually wrapping the patched fish config (`/opt/local/share/fish/config.fish`) in a `if status --is-login` block (as per https://github.com/berdario/pew#the-environment-doesnt-seem-to-be-activated) you can work around it.

What's your opinion on this?

**Comment by berdario** [comment]
Yes, changing their patch to either use `--is-login` or avoid prepending `/opt/local/bin` would make our users' life easier.

If you don't see any negative interaction, suggesting that change to Macports would be nice

**Comment by erinxocon** [comment]
@mbaechtold I'd recommend submitting a PR or change request for macports for this issue.  Closing the issue for now.  If you have any other questions let us know!
