### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by tuukkamustonen** [berdario/pew#164]
Maybe I'm blind but I can't seem to find release history for the project. Any plans to add one?

**Comment by berdario** [comment]
Yeah, there's no CHANGELOG, I always thought that the git log would've been enough for most uses.

But I should at least add some release notes to every release that I tag, do you think that would be enough, or do you need a separate CHANGELOG for some other reason?

**Comment by tuukkamustonen** [comment]
Well, it's quickest and simplest to just take a look at `CHANGELOG.md` that most projects provide these days. Or `HISTORY.rst`.

Going into git commits is nowhere near the convenience of simply taking a look at single file (in Github), that lists whole history of project in _human-readable_ form. `git log` contains bloat, bad/non-descriptive commit messages, etc. Plus if there are changes or upgrade instructions that you want to highlight, then you need a separate changelog.

Maintaining a changelog requires some effort (though not very much) but it's valuable to lazy/busy followers of the project.

**Comment by berdario** [comment]
Ok, but for all of that, it's probably still enough to rely on git tags.

Example:
https://github.com/purescript/purescript/releases

Don't expect me to keep the same quality and amount of details for my release notes, though:p

I have way less manpower than that other project

Do you think that would be enough?

**Comment by tuukkamustonen** [comment]
Purescript changelog looks good. While I think it's mostly constructed of commit messages(?), there are also clarifications for some items (plus very user-friendly `New Feature` blocks).

Doing changelog in git tags is actually nice because tools like https://sibbell.com may include the changelog in the notification about new release.

So yeah, following purescript-style is definitively a good start. Just remember to point to https://github.com/berdario/pew/releases from your `README.md` (like purescript does).

(FYI: There is also https://github.com/vaab/gitchangelog that auto-builds release notes from git log. You may want to check it out.)

**Comment by meshy** [comment]
A changelog sounds like a good idea to me. I'm a fan of the format suggested by https://keepachangelog.com/en/1.0.0/
