### ISSUE TITLE
Arrow keys don't work in pew shell on Windows

### ISSUE THREAD

**Issue by crioux** [berdario/pew#166]
In the normal CMD shell, usually you can hit 'up arrow' to get your previous command. Once you run 'pew in <some venv>' , this no longer works. 

if you run some commands inside the 'pew in' shell and then hit 'up' it does nothing.

It does work in 'ConEmu', so whatever they are doing in ConEmu to fix this might be useful to pew.

**Comment by erinxocon** [comment]
I'm gonna try and tackle this this week

**Comment by erinxocon** [comment]
Looks like this is a bug in virtualenv reported.  See ticket #165
