### ISSUE TITLE
cut a release

### ISSUE THREAD

**Issue by kennethreitz** [berdario/pew#178]

**Comment by berdario** [comment]
Can do, but I think that since the last release there haven't been meaningful changes beside test/setup improvements...

A big upcoming change is https://github.com/berdario/pew/pull/173 but I need to get the Windows tests to pass, before merging that

**Comment by kennethreitz** [comment]
yeah this is low priority for us now, actually.

**Comment by berdario** [comment]
Was this needed for https://github.com/pypa/pipenv/issues/1474 ?

@uranusjr mentioned that it might be doable after a new pew release

I could release now, I but I see that you just bumped the version in setup.py to 1.1.4 from 1.1.3, is 1.1.4 ready for release and we should skip 1.1.3?

(A release for this project means a new annotated tag and the tarball/wheel uploaded to Pypi... I already added Erin as maintainer, so I'm fine with others releasing bugfix releases on Pypi... just let's make sure that the tag contains some brief release notes)

**Comment by berdario** [comment]
I guess you might just have released a 1.1.3 to PPA for which `pew cp` was broken, and 1.1.4 fixes that... in which case, 1.1.4 has already been released over there.

So, this means that it'd be better to release the same versions (both of them) for upstream Pew, and not add any other small change to 1.1.4 (inconsistencies between the same versions could be really confusing).

**Comment by uranusjr** [comment]
Only thing needed on Pew’s part is the `__main__` module. After that Pipenv needs to change all direct `pew` calls to `python -m pew`, and that’s all.

**Comment by kennethreitz** [comment]
Yeah, we're planning to proceed with that as soon as you cut a release, basically :)

**Comment by berdario** [comment]
I released 1.1.3, 1.1.4 and 1.1.5

(I uploaded only the Wheels to pypi, though... twine is having issues with uploading the tarballs 🤔 )

Sorry for the delay 😞
