### ISSUE TITLE
pew workon doesn't source /etc/profile.d/*

### ISSUE THREAD

**Issue by peterdemin** [berdario/pew#186]
I have all system wide aliases defined in `/etc/profile.d/....sh` files but when I load pew virtual environment they all are not loaded. Like pew starts non-logon shell.

**Comment by berdario** [comment]
Yes, the fact that pew doesn't start a shell as a login shell [is intentional](https://github.com/berdario/pew#the-environment-doesnt-seem-to-be-activated) (it allows to customize a true login shell with different PATHs)

Not sure if this is anything that we should handle in Pew.

**Comment by peterdemin** [comment]
Thanks for explanation!
