### ISSUE TITLE
Pinned `psutil` dependency on Windows causes unnecessary conflicts

### ISSUE THREAD

**Issue by ankostis** [berdario/pew#192]
The `psutil` Windows-only dependency is pinned to version `5.3.1'.
In a python-installation with latest `psutil` this will cause it to downgrade from `5.4.3` (as of May 2018).
Is there any specific reason for the pinning?

[edit] My quick blame-search did not reveal the reason for the pinning: 02efd882

**Comment by pfmoore** [comment]
Further note - this causes failures when installing with Python 3.7, as there are no psutil 5.3.1 binaries for Python 3.7 (and I suspect it's unlikely they will be provided, as it's an out of date version).

I created #196 to add Python 3.7 support (remove the pins, add Python 3.7 to CI).

**Comment by pfmoore** [comment]
Fixed by #196 which has now been merged.
