### ISSUE TITLE
Wrong python executable version after creating new environment in AWS Linux

### ISSUE THREAD

**Issue by jnoortheen** [berdario/pew#194]
In a new AWS EC2 instance I installed pew using system's pip (also tried with pipsi). 

Then ran the following to create a python3.6 environment. But the python version is still pointing to 2.7 even after activating the venv.

![image](https://user-images.githubusercontent.com/6702219/41454856-a37e16de-7098-11e8-91c5-c2518f8ca843.png)

**Comment by pmav99** [comment]
I think that this is because you used the `-p` option after the name of the virtual environment. This should work:
``` bash
pew new -p `which python3` bf
```

**Comment by jnoortheen** [comment]
@pmav99 maybe. I am not able to reproduce that behavior anywhere else. I am closing the issue.
