### ISSUE TITLE
`pew in` needs to exit with an error code when the command is not found

### ISSUE THREAD

**Issue by mortenlj** [berdario/pew#200]
I had a problem in my CI build, where after some refactoring we noticed that our tests were not executed, but the build succeeded anyway. The reason turns out to be that when you run `pew in venv tox`, and `tox` isn't actually installed in `venv`, pew prints a helpful message about not finding `tox`, and exits with 0.

It would be nice if pew could exit with some other code when failing to execute the command.

**Comment by berdario** [comment]
Yeah, that's quite annoying for it to be failing silently :/

I thought of properly relaying the exit code already some time ago, there's no good reason that wouldn't have been done already.
I prepared a fix, will merge soon.

Thanks for the report!
