### ISSUE TITLE
Please upload sdist to PyPI

### ISSUE THREAD

**Issue by jayvdb** [berdario/pew#202]
The last few releases havent included a sdist on PyPI, instead they only have a wheel.

Also please include the tests in the sdist.

They are needed for packaging rpms, debs, etc.

I'd like https://build.opensuse.org/package/view_file/home:aboe76/python-pew/python-pew.spec?expand=1 to have tests so I can submit it to the main openSUSE repos.

Much appreciated.

**Comment by berdario** [comment]
I just uploaded 1.2.0 on pypi and I made sure to include the sdist

I forgot about modifying the MANIFEST to include the tests, though :man_facepalming: 

Can you use the github releases? those contain the whole source code (including tests)

https://github.com/berdario/pew/archive/1.2.0.tar.gz

**Comment by jayvdb** [comment]
An sdist is a distribution of the source, and tests are a vital part of that, and in this case they are a tiny addition.

```
> du -s tests
88      tests
```

We can use a GitHub archive, but then we miss differences between the github and pypi release, and that is a very frequent problem.

Would you like me to submit a PR to include the tests in MANIFEST.in - if I know the tests will be in the next sdist, whenever the next release happens, I will use the github archive for the initial submission into the main opensuse collection.

**Comment by berdario** [comment]
> Would you like me to submit a PR to include the tests in MANIFEST.in 

Yes please

I quickly tried to add them, but at the moment I cannot figure out how to include

__pycache__, tests/testpackage/dist tests/testpackage/build and test/testpackage/testpackage.egg-info (I tried with both recursive-exclude, whitelisting only `template_test` and `*.py` and with prune, but those files always end up being included)
