### ISSUE TITLE
Get pew to work with Prezto when the latter modifies $PATH

### ISSUE THREAD

**Issue by eth3lbert** [berdario/pew#29]
I've tried to use pew with pyenv, but it can't not get the right python bin path.
If i which python, it just return the system one(/usr/bin/python).

**Comment by sloria** [comment]
I am also having problems getting pew to work with prezto. 

Whenever I try run `pew new test` or `pew workon test`, I get an error:

```
New python executable in test/bin/python2.7
Not overwriting existing python script test/bin/python (you must use test/bin/python2.7)
Installing setuptools, pip...done.
ERROR: The virtualenv hasn't been activated correctly.
Either the env is corrupted (try running `pew restore env`),
Or an upgrade of your Python version broke your env,
Or check the contents of your $PATH. You might be adding new directories to it
from inside your shell's configuration file.
In this case, for further details please see: https://github.com/berdario/pew#the-environment-doesnt-seem-to-be-activated
```

Nothing special about my `$PATH`:

```
~/p/p/marshmallow ❯ echo $PATH | tr ':' '\n'                                                                                                                                         fix-validates-schema ✭
/Applications/Postgres.app/Contents/Versions/9.3/bin
/usr/local/bin
/usr/local/sbin
/usr/bin
/bin
/usr/sbin
/sbin
/opt/X11/bin
/usr/texbin
/Users/sloria/dotfiles/bin
```

**Comment by berdario** [comment]
@sloria 
Can you show me the output of `echo $PATH` side by side with `zsh -c 'echo $PATH'` ?

btw, I think i could apply the same workaround that I used for bash to zsh. With bash it was unavoidable, but since zsh is able to detect the problem correctly I'd rather not do it.

**Comment by sloria** [comment]
```
~ ❯ echo $PATH
/Applications/Postgres.app/Contents/Versions/9.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/Users/sloria/dotfiles/bin
~ ❯ zsh -c 'echo $PATH'
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/Applications/Postgres.app/Contents/Versions/9.3/bin:/usr/local/sbin:/Users/sloria/dotfiles/bin
```

I'll try out the workaround when I get back from dinner. Thanks for looking into this!

**Comment by berdario** [comment]
well, the workaround I was talking about is a workaround _inside_ pew: it'd amount to copy `.zshrc` to a temporary file, append at the end an `export PATH=correct path` and then run `zsh --rcs /path/to/tmp/zshrc`.

On your side, the easiest thing would be to pinpoint what exactly is modifying `$PATH` inside your `.zshrc` and fix that

**Comment by sloria** [comment]
Hm, I've tried to find everything in my dotfiles modifying `$PATH` and commenting them out, but still no luck. Will keep looking =/

**Comment by sloria** [comment]
Ah, the problem seems to be the buggy `/etc/zshenv` which runs path_helper. I was able to fix the problem by running

```
sudo mv /etc/zshenv /etc/zprofile
```

See:

- https://github.com/sorin-ionescu/prezto/issues/381
- https://github.com/thoughtbot/dotfiles/pull/426#issue-109716011

**Comment by berdario** [comment]
Thanks for digging that up. The second link seems to explain the problem with that configuration quite well, so I added it to the README.

Hopefully that will be enough for people to be able to understand and to fix it straight away, so I'm now closing this issue.

If you have any other suggestion to explain this better in the README, they're welcome :)

**Comment by AlJohri** [comment]
@berdario seems like I'm running into a very similar issue using `pyenv`. in the child process, the shell's zshrc/bashrc gets run which includes the pyenv's init command. pyenv's init prepends itself to the PATH causing the pyenv python to be the default as opposed to the virtualenv python. here is a test project that demonstrates the issue: https://github.com/AlJohri/test-pyenv-pipenv#test-pyenv-pipenv. notably, your `fork_bash` fix also fixes this issue. do you have any thoughts on a better long term solution either on the `pew` or `pyenv` side?

I'm primarily using zsh so wouldn't mind settling for a `fork_zsh` hack for now :)

**Comment by AlJohri** [comment]
@berdario thinking about this more, it seems like this isn't just a pyenv problem but a problem with anyone who modies the PATH in their bashrc/zshrc?

for example, if I put:
```bash
export PATH="/usr/local/bin/:$PATH"
```

in my zshrc file, wouldn't I end up using the system/homebrew python instead of the virtualenv python after running `pew workon xyz`?

**Comment by AlJohri** [comment]
ah, I see now that you addressed this in https://github.com/berdario/pew#the-environment-doesnt-seem-to-be-activated

however, the recommendation to use .bash_profile and .zprofile seems like it would only work on macOS since gui terminals are started as `login` sessions but this in linux all gui terminal sessions are `non-login`

i was thinking you can use `bash --noprofile --norc` and `zsh --no-rcs --no-globalrcs` but I see you mentioned in https://github.com/berdario/pew/issues/9#issuecomment-33187512 that shell functions won't get exported

perhaps the best solution is the hack you did for bashrc and repeating it for zsh as well?

**Comment by berdario** [comment]
@AlJohri I haven't had a look at your test project yet, but I'd rather avoid duplicate the fork_bash hack for other shells

anyhow

> however, the recommendation to use .bash_profile and .zprofile seems like it would only work on macOS since gui terminals are started as login sessions but this in linux all gui terminal sessions are non-login

![screenshot from 2017-10-01 05-25-52](https://user-images.githubusercontent.com/752835/31051762-0c688206-a669-11e7-97b8-0ad0111a8d9e.png)

**Comment by AlJohri** [comment]
Ah yes, I realize I was mistaken. Using zprofile / bash_profile should fix it indeed
