### ISSUE TITLE
Cannot download non-wheel dependencies

### ISSUE THREAD

**Issue by kwill** [berdario/pew#48]
**Steps to reproduce:**

* Using `pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)` on Ubuntu 14.10
* `pip install --download . pew` (correctly downloads wheels into current folder)
* `pip install --download . pew --no-use-wheel`

**What should happen:**
Correctly downloads tar.gz files into current folder

**What happens instead:**

```
Downloading/unpacking pew
  Using download cache from /home/username/.cache/pip/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fp%2Fpew%2Fpew-0.1.14.tar.gz
  Saved ./pew-0.1.14.tar.gz
  Running setup.py (path:/tmp/pip_build_username/pew/setup.py) egg_info for package pew
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_username/pew/setup.py", line 5, in <module>
        import pew
      File "pew/__init__.py", line 11, in <module>
        from . import pew
      File "pew/pew.py", line 12, in <module>
        from pathlib import Path
    ImportError: No module named pathlib
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_username/pew/setup.py", line 5, in <module>

    import pew

  File "pew/__init__.py", line 11, in <module>

    from . import pew

  File "pew/pew.py", line 12, in <module>

    from pathlib import Path

ImportError: No module named pathlib

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_username/pew
Storing debug log for failure in /home/username/.pip/pip.log
```

**Workaround:**
Works with `pip 6.0.6 from /home/username/.local/lib/python3.4/site-packages (python 3.4)` (that is, a non-system (`--user`) installation of the very latest version of pip; I'm not sure if running under Python 3 has anything to do with the workaround working.

**Comment by berdario** [comment]
Yeah, that's something I stumbled upon and that I can reproduce only with old pip versions.
Sorry, I'll fix this soon

**Comment by kwill** [comment]
Thanks! Hope this provides an easy-to-use test case.

**Comment by berdario** [comment]
After the [entry-points/imports refactoring](https://github.com/berdario/pew/commit/eeb2f1e307501444e06fceef4a9a2cd7fdd23a80) I think that this issue might be fixed.

Unfortunately I don't have access anymore to the virtual machine in which I could reproduce this error some months ago (I'd need to recreate it), so I'm not sure about closing this right away.
