### ISSUE TITLE
Cannot activate environment with pew on MacOs Yosemite

### ISSUE THREAD

**Issue by Cornoualis** [berdario/pew#50]
Hi there,
I installed pew on Yosemite using "pip install pew".
I cannot activate environments (wether they ware created with pew or with virtualenvwrapper) and have the "The environment doesn't seem to be activated" message.

I looked at the instructions given [here](https://github.com/berdario/pew#the-environment-doesnt-seem-to-be-activated), but, to be honest, I didn't really understand it.

I tried to put my "export PATH= ...." in a .zsh_proflie, but it didn't change anything.

Can anybody help?

Thanks in advance!

**Comment by berdario** [comment]
Hi, if you go with the .zsh_profile then you'd need to change/remove the PATH export in your .zshrc 

To help you, we'd need to see those 2 files, or at least the relevant parts of them. 
-- 
Sent from mobile. Please excuse my brevity.

**Comment by Cornoualis** [comment]
Here are my two files:

.zshrc:
```
    export ZSH=$HOME/.oh-my-zsh
    ZSH_THEME="pygmalion"
    plugins=(git docker pip rsync)
    source $ZSH/oh-my-zsh.sh
    export WORKON_HOME=$HOME/Dev/python/.virtualenv
    export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages 
    export PIP_VIRTUALENV_BASE=$WORKON_HOM
    export PIP_RESPECT_VIRTUALENV=true
    if [[ -r /Users/Cornoualis/Library/Python/2.7/bin/virtualenvwrapper.sh ]]; then
         source /Users/Cornoualis/Library/Python/2.7/bin/virtualenvwrapper.sh
    else
        echo "WARNING: Can't find virtualenvwrapper.sh"
    fi
```
.zsh_profile:
```
    export PATH="/usr/local/bin:/bin:/usr/sbin:/sbin:/Users/Cornoualis/Library/Python/2.7/bin:/usr/local/go/bin:/usr/bin"
```

Thanks for your help!

**Comment by Cornoualis** [comment]
Any news?

**Comment by ymage** [comment]
It seems zsh-related (same problem here). I tried with bash and problem does not occur.

**Comment by ymage** [comment]
I took a look deeper and the problem comes from the PATH entries order which is different for the subshell.
And this is already known here : https://github.com/berdario/pew/issues/29
Proposed workaround works for me.

**Comment by berdario** [comment]
Your .zshrc seems fine. Unfortunately from here I've no idea where your PATH is being modified.

The most likely culript from your paste is oh-my-zsh since it's one of the few lines that sources another script. The only way to be sure would be to try to comment out every such line (one at a time, or bisecting) to pinpoint the problem.

For now I'll leave this issue open, in case someone with the exact same setup might stumble upon it

**Comment by Erwhann-Rouge** [comment]
Try to rename your `.zsh_profile` to `.zprofile`.

I had the same issue on linux and this change seems to work.

**Comment by berdario** [comment]
Uhm, I never realized that the `.zsh_profile` that cornoualis talks about is not the correct configuration file... even in pew's README the correct one (`.zprofile`) is pointed out

I guess this can be closed
