### ISSUE TITLE
Add tab completion

### ISSUE THREAD

**Issue by Vayel** [berdario/pew#51]
I don't know if it's possible but it would be convenient to have the tab completion available with the `pew workon` command (and maybe with some others I don't use).

**Comment by arthru** [comment]
Completion scripts are available in https://github.com/berdario/pew/tree/master/pew/complete_scripts

**Comment by Vayel** [comment]
Is it activated by default? I'm sorry, but it seems not to work. Pressing the Tab key after `pew workon` only displays available directories.

**Comment by berdario** [comment]
No, they are not activated by default

executing `lib/python3.4/site-packages/pew/complete_scripts/complete_deploy` should be enough to enable them for Ubuntu.

with a simple well-behaved python package you don't put things into random location on disk, but I agree that this could be taken care of by the (e.g.) .deb package

Let me know (and/or just open a PR) if you know of a portable way to programmatically deploy and make available these completions on the different linux distros (and maybe also MacOSX, for good measure)

Still, this needs to be documented a bit more.

Thank you

**Comment by Vayel** [comment]
I can't run it without being root.

```
$ /usr/lib/python2.7/site-packages/pew/complete_scripts/complete_deploy 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pew/complete_scripts/complete_deploy", line 4, in <module>
    deploy_completions()
  File "/usr/lib/python2.7/site-packages/pew/pew.py", line 66, in deploy_completions
    shutil.copy(str(inve_site / 'complete_scripts' / comp), str(dest))
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/etc/bash_completion.d/pew'
```

**Comment by berdario** [comment]
After [this change](https://github.com/berdario/pew/commit/c3f2dc24a3c25a035e5b1640925498418b596421) there's another way to get shell completions:

assuming that your `SHELL` is `bash` (otherwise you need `$(env SHELL=bash pew completions)` to have bash completions while having another default shell), you can for example add

`source $(pew completions)`

in your `.bashrc`

I'll update the readme before the new release

**Comment by maxbellec** [comment]
command is now `source $(pew shell_config)` (at least for version `1.2.0`)
