### ISSUE TITLE
Upgrade pip

### ISSUE THREAD

**Issue by Vayel** [berdario/pew#57]
```
[vincent@vincent crossbar]$ pew new test
New python executable in test/bin/python
Installing setuptools, pip...done.
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
(test) [vincent@vincent crossbar]$ pip install pew
You are using pip version 6.0.3, however version 6.0.8 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I don't know how pip is installed during the creation of the env but maybe you could run `pip install --upgrade pip` automatically, couldn't you? And so could you with setuptools.

**Comment by berdario** [comment]
Using the same version of pip (6.0.3) I cannot reproduce this problem.

    py27  dario@feynman ~/P/pew (master)> pip --version
    pip 6.0.3 from /home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages (python 2.7)
    py27  dario@feynman ~/P/pew (master)> pew new test
    Using real prefix '/usr'
    New python executable in test/bin/python2.7
    Also creating executable in test/bin/python
    Installing setuptools, pip, wheel...done.
    Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
    test  dario@feynman ~/P/pew (master)> pip install pew
    Collecting pew
     Using cached pew-0.1.14-py2.py3-none-any.whl
    Collecting virtualenv>=1.11 (from pew)
     Using cached virtualenv-13.1.2-py2.py3-none-any.whl
    Collecting virtualenv-clone>=0.2.5 (from pew)
    Collecting pathlib (from pew)
    Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.8 in /home/dario/.local/share/virtualenvs/test/lib/python2.7/site-packages (from pew)
    Installing collected packages: virtualenv, virtualenv-clone, pathlib, pew
    Successfully installed pathlib-1.0.1 pew-0.1.14 virtualenv-13.1.2 virtualenv-clone-0.2.6
    test  dario@feynman ~/P/pew (master)> pip --version
    pip 7.1.2 from /home/dario/.local/share/virtualenvs/test/local/lib/python2.7/site-packages (python 2.7)

Installation of pip+setuptools is taken care by virtualenv. Obviously I could run `pip install --upgrade pip` automatically as suggested.
Maybe virtualenv upstream is now ensuring to use the latest version automatically?

**Comment by berdario** [comment]
Disregard what I wrote previously, pip is not downloaded by virtualenv (obviously), but it's shipped with it.

    py27  dario@feynman ~/P/pew (master) [2]> 
    pip install --upgrade virtualenv==12.0.7 
    You are using pip version 6.0.3, however version 7.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Collecting virtualenv==12.0.7
     Downloading virtualenv-12.0.7-py2.py3-none-any.whl (1.8MB)
       100% |################################| 1.8MB 1.3MB/s 
    Installing collected packages: virtualenv
     Found existing installation: virtualenv 13.1.2
       Uninstalling virtualenv-13.1.2:
         Successfully uninstalled virtualenv-13.1.2
    
    Successfully installed virtualenv-12.0.7
    py27  dario@feynman ~/P/pew (master)> virtualenv --version
    12.0.7
    py27  dario@feynman ~/P/pew (master)> pew new test
    Using real prefix '/usr'
    New python executable in test/bin/python2.7
    Also creating executable in test/bin/python
    Installing setuptools, pip...done.
    Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
    test  dario@feynman ~/P/pew (master)> pip --version
    pip 6.0.8 from /home/dario/.local/share/virtualenvs/test/local/lib/python2.7/site-packages (python 2.7)
    test  dario@feynman ~/P/pew (master)> pip install pew
    You are using pip version 6.0.8, however version 7.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.

Again, I could force an update of pip, but since virtualenv will just use the version of pip that is shipped with it, the better approach would be to make sure that pew is installed with the latest virtualenv version

`pip install --upgrade virtualenv`

then, every new virtualenv will have the latest pip. Installing it at the creation of a new env would also yield errors in case connection is unavailable (I could test for that, but then this start to be a bit too complex).
