### ISSUE TITLE
Python 3.4.2 everywhere

### ISSUE THREAD

**Issue by Vayel** [berdario/pew#58]
I can't create an env with Python 2:

```
[vincent@vincent crossbarwww]$ python
Python 3.4.2 |Continuum Analytics, Inc.| (default, Oct 21 2014, 17:40:08) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
[vincent@vincent crossbarwww]$ python2.7
Python 2.7.5 (default, Feb 19 2014, 13:47:40) 
[GCC 4.8.2 20131212 (Red Hat 4.8.2-7)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
[vincent@vincent crossbarwww]$ pew new -p python2.7 test
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in test/bin/python2.7
Also creating executable in test/bin/python
Installing setuptools, pip...done.
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
(test) [vincent@vincent crossbarwww]$ python -V
Python 3.4.2 :: Continuum Analytics, Inc.
(test) [vincent@vincent crossbarwww]$
```

Thanks.

**Comment by berdario** [comment]
That's weird

Which version of pew are you using? if it's at least 0.1.12 you should be warning of potential problems with the PATH

Can you give me the value of $PATH inside and outside of the virtualenv subshell?

I assume you're using zsh, can you paste the relevant lines of your .zshrc that modify your $PATH?

Thank you

**Comment by Vayel** [comment]
```
[vincent@vincent Prog]$ pew version
0.1.14
[vincent@vincent Prog]$ echo $PATH
/home/vincent/miniconda3/bin:/home/vincent/miniconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/vincent/.local/bin:/home/vincent/bin
[vincent@vincent Prog]$ pew new test -p python2.7
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in test/bin/python2.7
Also creating executable in test/bin/python
Installing setuptools, pip...done.
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
(test) [vincent@vincent Prog]$ echo $PATH
/home/vincent/miniconda3/bin:/home/vincent/.local/share/virtualenvs/test/bin:/home/vincent/miniconda3/bin:/home/vincent/miniconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/vincent/.local/bin:/home/vincent/bin
(test) [vincent@vincent Prog]$
```

Would miniconda be responsible for this?

```
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
function opencvcompile {
	g++ "$1".cpp -o "$2$1" `pkg-config --cflags --libs opencv`
}

# AZERTY
setxkbmap fr

PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
export PKG_CONFIG_PATH

# pew
function venv_ps1(){
    test -n "$VIRTUAL_ENV" && echo "($(basename "$VIRTUAL_ENV")) "
}
PS1="$(venv_ps1)$PS1"

# added by Miniconda3 3.8.3 installer
export PATH="/home/vincent/miniconda3/bin:$PATH"
```

Thanks!

**Comment by berdario** [comment]
Yup

Try to move

```
export PATH="/home/vincent/miniconda3/bin:$PATH"
```

inside your `.bash_profile` (create it if absent)

Still, pew should warn you for this issue, I'll try to have a look at the code, and later to actually install miniconda and try to do the same

Unfortunately I dropped the ball a bit in the last month, plenty of things are happening and I haven't been able to merge the other PRs :/

**Comment by Vayel** [comment]
It works. Thanks a lot.

**Comment by Vayel** [comment]
Miniconda is really annoying:

```
[vincent@vincent moveonclick]$ pew new tartopum -p python3
Running virtualenv with interpreter /home/vincent/miniconda3/bin/python3
Using base prefix '/home/vincent/miniconda3'
New python executable in tartopum/bin/python3
Also creating executable in tartopum/bin/python
tartopum/bin/python3: error while loading shared libraries: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory
ERROR: The executable tartopum/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/home/vincent/.local/share/virtualenvs' (should be '/home/vincent/.local/share/virtualenvs/tartopum')
ERROR: virtualenv is not compatible with this system or executable
[vincent@vincent moveonclick]$
```

Thanks.

**Comment by berdario** [comment]
Which version of virtualenv do you have outside the virtualenv? it should be >=1.11

**Comment by Vayel** [comment]
```
$ pip show virtualenv
---
Name: virtualenv
Version: 1.11.6
Location: /home/vincent/.local/lib/python2.7/site-packages
```

**Comment by berdario** [comment]
If you `pip install --upgrade virtualenv`, does it fix it?

**Comment by Vayel** [comment]
Unfortunately, it doesn't.

```
[vincent@vincent components]$ pip show virtualenv
---
Name: virtualenv
Version: 12.0.7
Location: /usr/lib/python2.7/site-packages
Requires: 
[vincent@vincent components]$ pew new tartopum -p python3
Running virtualenv with interpreter /home/vincent/miniconda3/bin/python3
Using base prefix '/home/vincent/miniconda3'
New python executable in tartopum/bin/python3
Also creating executable in tartopum/bin/python
tartopum/bin/python3: error while loading shared libraries: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory
ERROR: The executable tartopum/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/home/vincent/.local/share/virtualenvs' (should be '/home/vincent/.local/share/virtualenvs/tartopum')
ERROR: virtualenv is not compatible with this system or executable
[vincent@vincent components]$
```

Would the problem come from this?

```
# added by Miniconda3 3.8.3 installer
export PATH="/home/vincent/miniconda3/bin:$PATH"
```

**Comment by berdario** [comment]
For people that might be wondering: I haven't abandoned this project

still, I'm still in probation with my new job, and before fixing/adding any other feature, I wanted to get this sorted out... and the lack of correct warning messages for bash is a serious issue

I tried a couple months ago to find a solution for it, but bash does something really weird, I spent some time trying to understand the behavior of ttys, but I couldn't find anything better than "parsing the .bashrc with regexps" (unfortunately bash doesn't have a proper syntax, and so it's impossible to even parse the file to answer a question as simple as: "is this variable going to be assigned a value, any value?")

http://unix.stackexchange.com/questions/187738/invoke-subshell-command-with-loaded-rcfile

Now, I was thinking that [my idea from last year](https://github.com/berdario/pew/issues/9#issuecomment-33178350) of not relying on the default .bashrc might not be so bad, after all. I was looking into how [`nix-shell`](https://github.com/NixOS/nix/blob/deb8668a0eb6b51a791e48942e6c91/scripts/nix-build.in#L285) does things, and apparently it's creating its own `.bashrc` file

So, I thought that a possibly-simpler solution could be to copy `.bashrc` to a temporary directory, append `'export PATH = ' + os.environ['PATH']` to it, and source that... but the `--rcfile` still doesn't behave as I expect it to.

**Comment by berdario** [comment]
Ok, I'm not quite sure why, since I remember having tried `pty.spawn` already back in february/march, but with that it can apparently work, and I created a branch for that:

https://github.com/berdario/pew/tree/bash_pty_fix

unfortunately, while it works interactively... the behavior is different enough that it would require having the tests written differently for bash (if it's at all possible to do it)

So, now I implemented the `.bashrc` workaround I was talking about

If someone wants to try it out, feedback is welcome

**Comment by berdario** [comment]
As I mentioned earlier, the [workaround](https://github.com/berdario/pew/commit/553e3383974f301fffb05da547d5576dd8a756a0) prevents the original issue.
About the second problem, I spent a bit of time again to try miniconda, and it seems to be incompatible with virtualenv itself.
Or at least, interoperability with virtualenv is not well tested (which is understandable, since conda has its own way to create envs and manage them):

    virtualenv --python=/home/dario/miniconda3/bin/python3 duh
    Running virtualenv with interpreter /home/dario/miniconda3/bin/python3
    Using base prefix '/home/dario/miniconda3'
    New python executable in duh/bin/python3
    Also creating executable in duh/bin/python
    Installing setuptools, pip...
      Complete output from command /tmp/duh/bin/python3 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
      Ignoring indexes: https://pypi.python.org/simple/
    Exception:
    Traceback (most recent call last):
      File "/home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/basecommand.py", line 122, in main
        status = self.run(options, args)
      File "/home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/commands/install.py", line 236, in run
        session = self._build_session(options)
      File "/home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/basecommand.py", line 52, in _build_session
        session = PipSession()
      File "/home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/download.py", line 216, in __init__
        super(PipSession, self).__init__(*args, **kwargs)
      File "/home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 273, in __init__
        self.headers = default_headers()
      File "/home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/requests/utils.py", line 555, in default_headers
        'User-Agent': default_user_agent(),
      File "/home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/requests/utils.py", line 524, in default_user_agent
        _implementation = platform.python_implementation()
      File "/home/dario/miniconda3/lib/python3.4/platform.py", line 1319, in python_implementation
        return _sys_version()[0]
      File "/home/dario/miniconda3/lib/python3.4/platform.py", line 1282, in _sys_version
        repr(sys_version))
    ValueError: failed to parse CPython sys.version: '3.4.3 (default, Mar 26 2015, 22:07:14) \n[GCC 4.9.2]'
    
    Storing debug log for failure in /tmp/tmpuldea5rg
    ----------------------------------------
    ...Installing setuptools, pip...done.
    Traceback (most recent call last):
      File "/home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages/virtualenv.py", line 2338, in <module>
        main()
      File "/home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages/virtualenv.py", line 824, in main
        symlink=options.symlink)
      File "/home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages/virtualenv.py", line 992, in create_environment
        install_wheel(to_install, py_executable, search_dirs)
      File "/home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages/virtualenv.py", line 960, in install_wheel
        'PIP_NO_INDEX': '1'
      File "/home/dario/.local/share/virtualenvs/py27/local/lib/python2.7/site-packages/virtualenv.py", line 902, in call_subprocess
        % (cmd_desc, proc.returncode))
    OSError: Command /tmp/duh/bin/python3 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 2    

I get a different error... There are [ways around that](http://stackoverflow.com/questions/21635107/pip-executes-the-wrong-python-library-versions-inside-virtual-env). But supporting these conditions seems out of scope for pew (I guess that the only true solution would be to reimplement parts of conda inside pew)
