### ISSUE TITLE
Cannot use without sudo

### ISSUE THREAD

**Issue by louy2** [berdario/pew#59]
I am using Arch Linux x64, installing with `sudo pip install pew`. I cannot install without `sudo`.

But now I cannot use `pew` without `sudo` either. I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/pew", line 7, in <module>
    from pew.pew import pew
ImportError: No module named 'pew.pew'
```

**Comment by jlesquembre** [comment]
Why don't you use the arch package?
https://aur.archlinux.org/packages/python-pew/

**Comment by louy2** [comment]
I am writing a provision script and AUR package is a lot harder than `pip`. I guess I have to try `yaourt` this time. Is other distributions different from Arch managing privilege of `/usr/bin`?

**Comment by louy2** [comment]
Success with `yaourt`.

**Comment by jlesquembre** [comment]
You don't need yaourt to install an AUR package:  
    
    curl -O https://aur.archlinux.org/packages/py/python-pew/PKGBUILD
    makepkg
    sudo pacman -U python-pew-0.1.14-1-any.pkg.tar.xz

**Comment by louy2** [comment]
I know. I am just lazy.  (> v O)
