### ISSUE TITLE
"pew wipenv" uninstalls packages from the main environment

### ISSUE THREAD

**Issue by BartGo** [berdario/pew#61]
```pew in MYENV pew wipeenv``' uninstalls all packages from MYENV which is good.

But when executed directly (``pew wipenv``), which is quite easy to do by someone learning how to use pew, packages from the *system Python* are uninstalled which should not happen that easily. A nicer solution would be to fail when we are outside virtual env or at least require a switch like --force in such cases.

Checked on Windows / cmd.exe and on Windows / Git Bash, Python 2.7.10 and:
pathlib==1.0.1
pew==0.1.14
virtualenv==13.0.1
virtualenv-clone==0.2.5

**Comment by berdario** [comment]
Good point. I hope discovering this wasn't too painful for you.

I'll probably add a `-y` flag. That should solve this issue and also prevent unintended wiping inside a virtualenv.

**Comment by BartGo** [comment]
It wasn't too painful, actually wiping served it well... You could also consider changing syntax of the command so it becomes simply ``pew wipeenv MYENV`` with obligatory MYENV and does not require usage of ``pew in``.
