### ISSUE TITLE
Running in git-bash switches to Power Shell mode!?

### ISSUE THREAD

**Issue by drozzy** [berdario/pew#66]
Running `pew` command in git-bash on Windows, switches the whole thing to weird powershell mode, which intermittently goes back to git-bash.

Really bizzare, and doesn't work as expected I presume.

**Comment by ryanhiebert** [comment]
I don't currently have a windows box to test. How would you determine which shell is currently running on Windows? We've just said "if it's windows, open powershell", which is obviously not correct for you.

Perhaps we can check the `SHELL` environment variable, and default to powershell if nothing is set there.

**Comment by BartGo** [comment]
workaround: pew in myenv bash

**Comment by berdario** [comment]
Indeed, that's bizarre. When I first wrote support for windows I assumed that people would use pew only inside powershell.

Now it's [fixed](https://github.com/berdario/pew/commit/6a1ac719089d434082c3414c2ea1cf8fcc516bac)

Thank you, and let me know if it doesn't work properly

(I'll make a release soon)
