### ISSUE TITLE
Tab-completion breaks in zsh with $(pew shell_config)

### ISSUE THREAD

**Issue by sloria** [berdario/pew#69]
After running `source $(pew shell_config)` in either my `.zshrc`, `.zprofile`, or on the command-line, tab-completion goes a bit wonky.

Before and after running the shell_config (notice how `ls` gets duplicated after pressing tab):

![shell_config_bug](https://cloud.githubusercontent.com/assets/2379650/10500192/7717ccce-72a4-11e5-8ce5-71eaaa3dd096.gif)

I suspect that it might be a bad interaction with one of prezto's runtime modules.

**Comment by berdario** [comment]
Uh, no... it's not a problem with prezto, it seems to be broken by default on zsh :/

The zsh completion wasn't written by me... this is the original one:

https://github.com/berdario/pew/commit/35e37f720345753ff644bb4c3e609755fcd7a7f0

Maybe [this change](https://github.com/berdario/pew/commit/9cb629a7bc2bfcd7553029b96f563611f80f5f9a#diff-92c96f8da306eede8ca0b8a4478b1e90) was the cause for the breakage?

if you can patch the `complete.zsh`, I'd gladly merge a fix right away

**Comment by sloria** [comment]
Ah ok, modified the title accordingly. I also probably won't be able to patch this anytime soon. At least until https://github.com/berdario/pew/issues/29 is resolved , I won't be able to use pew and therefore can't effectively debug this issue.

**Comment by sloria** [comment]
The problem seems to be coming from the loading `colors` here: https://github.com/berdario/pew/blob/3dafeb5adadf96ed62cae89790d7c45f59cec64f/pew/shell_config/init.zsh#L4 . 

Commenting that line out fixes the problem. 

I ended up with the following in my `.zshrc`:

```
function virtualenv_prompt_info() {
    if [ -n "$VIRTUAL_ENV" ]; then
        local name=$(basename $VIRTUAL_ENV)
        echo "($name)"
    fi
}
PS1="$(virtualenv_prompt_info)$PS1"
```

which gives me 

![1__tmux](https://cloud.githubusercontent.com/assets/2379650/10505457/a3316aa4-72db-11e5-8ec0-06fc6b3367e5.png)

If you'd like, I can send a PR adding the above to the `init.zsh`. Or, if you don't like the `()`, I can just remove the `autoload -U colors...` for now. It's up to you.

**Comment by berdario** [comment]
Thank you, nice catch!

I'd really like to understand why `colors` is affecting the tab-completion.

Anyhow, I'd prefer to use colors rather than parentheses (it'd save 1 or 2 characters while still clearly differentiating it), but if colors cannot be used, `()` are just fine.

**Comment by kalekseev** [comment]
The problem is that `$reset_color` wasn't escaped properly `%{$reset_color%}`
