### ISSUE TITLE
Could pew add the env name in the $PS1?

### ISSUE THREAD

**Issue by Natim** [berdario/pew#72]
One thing that I like with pew is to be able to exist the virtualenv using ctrl+D, one thing that bothers me is that I don't know in which venv I am.

Would it be possible to add a ``|venv_name|`` before the PS1 so that it is possible to know in which venv we currently are with pew?

**Comment by Natim** [comment]
Ok this seems to be something already present in the README.

## Display the environment name in the terminal prompt

The first run setup should take care of this for you.
You can do it manually by appending to your `.bashrc`/`.zshrc`

``source $(pew shell_config)``

**Comment by berdario** [comment]
Good that the README has been useful :)

I wonder: did you miss the first-run-setup because of switching to pew from virtualenvwrapper, or for another reason?

**Comment by Natim** [comment]
> did you miss the first-run-setup because of switching to pew from virtualenvwrapper

Probably yes, I did that step before running pew the first time:

    ln -s ~/.virtualenvs ~/.local/share/virtualenvs
