### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by kierun** [berdario/pew#75]
I just tried to install pew using pip 1.7.2 and got this error:

    ; python -V
    Python 2.7.5
    ; pip --version
    pip 7.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
    ; pip install --user pew
    Collecting pew
      Using cached pew-0.1.18-py2.py3-none-any.whl
    Collecting pythonz-bd>=1.10.2 (from pew)
      Using cached pythonz-bd-1.10.2.tar.gz
      Complete output from command python setup.py egg_info:
      error in pythonz-bd setup command: Invalid environment marker: python_version>="3.5"
      ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ngA0LP/pythonz-bd

**Comment by berdario** [comment]
Sorry, this is #71 
I believed that `pip install --upgrade pip` would've been enough, but this is obviously not the case.

I'll update the README soon, and see if I should do something else as well
