### ISSUE TITLE
Exception when prompt contains Unicode symbol

### ISSUE THREAD

**Issue by mbollmann** [berdario/pew#76]
My bash prompt contains [a unicode symbol](http://www.fileformat.info/info/unicode/char/21af/index.htm).

When I try to perform `pew workon`, it fails with a UnicodeEncodeError:

```
Traceback (most recent call last):
  File "/usr/local/bin/pew", line 11, in <module>
    sys.exit(pew())
  File "/usr/local/lib/python2.7/dist-packages/pew/pew.py", line 684, in pew
    return command(sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/pew/pew.py", line 322, in workon_cmd
    shell(env, cwd=project_dir)
  File "/usr/local/lib/python2.7/dist-packages/pew/pew.py", line 172, in shell
    fork_bash(env, cwd)
  File "/usr/local/lib/python2.7/dist-packages/pew/pew.py", line 150, in fork_bash
    rcfile.write(bashrc.read())
UnicodeEncodeError: 'ascii' codec can't encode character u'\u21af' in position 2223: ordinal not in range(128)
```

If I remove the offending symbol from my prompt, everything works as intended. (pew version 0.1.18)

**Comment by mbollmann** [comment]
It seems I can just circumvent this by explicitly running pew with Python 3.x, but it doesn't say anywhere that this is required as far as I could see ...

**Comment by berdario** [comment]
I have some unicode characters as well in my git prompt. Nowadays I'm always using pew on top of Python3, but it should still work on Python2

I'll try to have a look at it later on, sorry for the inconvenience!

**Comment by berdario** [comment]
Fixed.

Getting the same semantics on Python2 is painful sometimes :/
