### ISSUE TITLE
cannot install using chocolatey

### ISSUE THREAD

**Issue by timeyyy** [berdario/pew#78]
pew isn't even listed as a package on chocolatey..

https://chocolatey.org/packages?q=pew
```
Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - pew
```

**Comment by berdario** [comment]
The command was

`choco python pew`

Chocolatey apparently removed this command in the last few versions... now it's

`choco install pew --source python`

https://github.com/chocolatey/choco/wiki/CommandsInstall#alternative-sources

But they write:

> NOTE: THIS IS NOT YET REIMPLEMENTED. TODO: Draw out what each of these is (links/documentation)

So, apparently they removed support for it: even by trying their example with sphinx it fails: `choco install sphinx --source python`

So, this is not a bug with Pew. I'm not sure if I should update the README by pointing out that now it doesn't work and might work again in the future... Or keep this bug open until they'll actually fix it to work again.

Obviously, a proper chocolatey package would be a nice solution, but it's imho not worth the effort.

Thank you for pointing this out, btw!

**Comment by timeyyy** [comment]
If it is not working at this time just delete it from the read me imo. Pip seems to work fineon windows so :-)
