### ISSUE TITLE
Problem with whitespaces in $ORIGINAL_PATH : invalid identifier

### ISSUE THREAD

**Issue by Lucas-C** [berdario/pew#82]
I don't know how, but under Cygwin, at some point after sourcing my `.bashrc`, `pew` uses the value of `$ORIGINAL_PATH` without taking care of whitespaces in it.

I put this in my `.bashrc` to get extra info logged:
````
echo "ORIGINAL_PATH=$ORIGINAL_PATH"
echo "PATH=$PATH"
```

And here is the result:
````
$ pew workon test-requests-security
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
ORIGINAL_PATH=/cygdrive/c/devhome/tools/jdk1.8.0_40/bin:/cygdrive/c/devhome/tools/apache-maven-3.3.3/bin:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/devhome/tools/Python27:/cygdrive/c/devhome/tools/Python34:/cygdrive/c/Program Files/nodejs:/cygdrive/c/HashiCorp/Vagrant/bin:/cygdrive/g/devhome/tools/php-5.6.8:/cygdrive/c/Program Files/MySQL/MySQL Workbench 6.2 CE:/cygdrive/c/Program Files/Boot2Docker for Windows:/cygdrive/c/Program Files (x86)/Nmap:/cygdrive/d/Users/lucas_cimon/AppData/Roaming/Composer/vendor/bin:/cygdrive/c/Program Files/TortoiseSVN/bin:/cygdrive/c/Program Files/Puppet Labs/Puppet/bin:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit
PATH=/home/lucas_cimon/.local/share/virtualenvs/test-requests-security/bin:/home/lucas_cimon/.local/bin/:/home/lucas_cimon/gocode/bin:/tmp/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
bash: export: « Files/Boot2Docker » : identifiant non valable
bash: export: « Windows:/c/Program » : identifiant non valable
bash: export: « Files/nodejs:/c/Program » : identifiant non valable
bash: export: « Files/Oracle/VirtualBox:/c/Program » : identifiant non valable
bash: export: « Files/Puppet » : identifiant non valable
bash: export: « Labs/Puppet/bin:/c/HashiCorp/Vagrant/bin:/d/Users/lucas_cimon/AppData/Roaming/npm:/d/Users/lucas_cimon/AppData/Roaming/Composer/vendor/bin:/g/devhome/tools/apache-maven-3.3.3/bin:/g/devhome/tools/elasticsearch/bin:/g/devhome/tools/lcdf-typetools/bin:/g/devhome/tools/volatility_2.5.win.standalone:/cygdrive/c/devhome/tools/jdk1.8.0_40/bin:/g/devhome/tools/apache-tomcat-7.0.52/bin:/home/lucas_cimon/gems/bin:/home/lucas_cimon/bin » : identifiant non valable
```

The error messages are in French sorry, but "identifiant non valable" translates to "invalid identifier".

It looks like `$ORIGINAL_PATH`, a Cywgin-specific environment variable, is used somehow after the `.bashrc` is loaded, and not the `$PATH`, which contains no whitespaces.

**Comment by berdario** [comment]
If I remember correctly, your fix in d581277a6a29573cca5e25e21eceb9fd8e59b28c takes care of this
