### ISSUE TITLE
Saving tmpenv

### ISSUE THREAD

**Issue by Phyks** [berdario/pew#86]
Hi,

I often `pew mktmpenv` to run some code. After a while, I sometimes realize I actually want to keep this venv. Is there a way to save it under some name afterwards (could not find it)? Else, I think it would be a great new feature!

Thanks!

**Comment by berdario** [comment]
Thanks, indeed this use case hasn't been thought about before

You can anyhow accomplish what you asked with `pew cp`:

    pew  dario@feynman ~/P/pew (master)> pew mktmpenv --python=python3.5
    Running virtualenv with interpreter /home/dario/Applications/bin/python3.5
    Using base prefix '/home/dario/.pythonz/pythons/CPython-3.5.0'
    New python executable in 4ff159190479760/bin/python3.5
    Also creating executable in 4ff159190479760/bin/python
    Installing setuptools, pip, wheel...done.
    This is a temporary environment. It will be deleted when you exit
    Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
    4ff159190479760  dario@feynman ~/P/pew (master)> pip install inquirer
    Collecting inquirer
     Downloading inquirer-2.1.6.tar.gz
    Collecting blessings>=1.5.1 (from inquirer)
     Downloading blessings-1.6.tar.gz
    Collecting readchar==0.7 (from inquirer)
     Downloading readchar-0.7.tar.gz
    Building wheels for collected packages: inquirer, blessings, readchar
     Running setup.py bdist_wheel for inquirer
     Stored in directory: /home/dario/.cache/pip/wheels/b9/8c/30/94325753c9adca00b0d41eebbcb24483e89162958a9dda9778
     Running setup.py bdist_wheel for blessings
     Stored in directory: /home/dario/.cache/pip/wheels/f3/c9/62/5c19370a7e3b1a8221411d67be2f483e4b1a44b0a9fb2d1217
     Running setup.py bdist_wheel for readchar
     Stored in directory: /home/dario/.cache/pip/wheels/fd/b6/26/319a717eaf7c5c9a9cf8215e0157135cebbb615a359f644a7d
    Successfully built inquirer blessings readchar
    Installing collected packages: blessings, readchar, inquirer
    Successfully installed blessings-1.6 inquirer-2.1.6 readchar-0.7
    You are using pip version 7.1.2, however version 8.0.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    4ff159190479760  dario@feynman ~/P/pew (master)> pew cp 4ff159190479760 not-temp
    Copying /home/dario/.local/share/virtualenvs/4ff159190479760 in not-temp
    Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
    not-temp  dario@feynman ~/P/pew (master)> exit
    
    4ff159190479760  dario@feynman ~/P/pew (master)> exit
    
    pew  dario@feynman ~/P/pew (master)> pew workon not-temp
    Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
    not-temp  dario@feynman ~/P/pew (master)> python
    Python 3.5.0 (default, Sep 14 2015, 09:43:40) 
    [GCC 4.9.2] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import inquirer
    >>> inquirer.__file__
    '/home/dario/.local/share/virtualenvs/not-temp/lib/python3.5/site-packages/inquirer/__init__.py'
    >>> 


`pew cp` relies con `virtualenv-clone` which is known to have problems on Windows and might have other latent bugs.

Let me know if it doesn't work for you, and I can either see to fix it or maybe add some other command

**Comment by Phyks** [comment]
Ok. Thanks! Having an alias for it would be useful though :)
