### ISSUE TITLE
Please support paths with whitespaces in $PATH

### ISSUE THREAD

**Issue by Lucas-C** [berdario/pew#94]
Hello,

It'd be great if `pew` could be used on system where the `$PATH` contains paths with whitespaces (and also `(` characters btw, they are very frequent under Windows for programs installed in the `Program Files (X86)` directory).

With Bash, I think only a minor edit on https://github.com/berdario/pew/blob/master/pew/pew.py#L106 would be needed, so that the $PATH returned by `compute_path` is enclosed in double quotes.

What do you think ? Are you open to a PR ?

**Comment by berdario** [comment]
Definitely! 

I'm a bit uncertain though:

If the issue is the whole $PATH being splitted, and if it's bash specific, I think the correct place to fix it would be at line 154, though 
-- 
Sent from mobile. Please excuse my brevity.

**Comment by Lucas-C** [comment]
Ok, I'm sending you a PR

**Comment by berdario** [comment]
Thank you!

I plan to make a release this evening
